# Localization.ps1 - Multi-language support (FR, EN, ES, IT)

$Script:CurrentLanguage = "FR"

$Script:Strings = @{
    # ============================================================
    # FRANCAIS
    # ============================================================
    "FR" = @{
        # --- App ---
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "Export DataBlocks TIA Portal"

        # --- Update ---
        UpdateBannerText  = "Mise a jour v{0} disponible. Le telechargement automatique a echoue (verifiez la connexion reseau)."
        BtnUpdateDownload = "Telecharger"
        TipUpdateDownload = "Ouvrir la page de telechargement de la derniere version"

        # --- Navigation ---
        NavConnection     = "Connexion"
        NavExport         = "Export DataBlocks"

        # --- Version ---
        LblVersion        = "Version TIA Portal :"
        LblNoVersion      = "Aucune version TIA Portal detectee."
        LblDllError       = "Erreur de chargement DLL"
        LblVersionLocked  = "Version verrouillee (connecte)"
        LblVersionPending = "Version {0} selectionnee (chargee au premier scan)."
        LblVersionLoadedLocked = "Version {0} chargee. Redemarrez l'outil pour en changer."

        # --- Connection Page ---
        PageConnection    = "Connexion TIA Portal"
        BtnScan           = "Scanner les instances TIA Portal"
        LblInstances      = "Instances disponibles"
        BtnConnect        = "Se connecter"
        BtnDisconnect     = "Se deconnecter"
        LblConnected      = "Connecte"
        LblDisconnected   = "Deconnecte"
        LblScanResult     = "{0} instance(s) trouvee(s)"
        LblNoInstance     = "Aucune instance TIA Portal trouvee"
        LblScanVersionMismatch = "TIA Portal {0} est ouvert mais la version chargee est {1}. Fermez puis rouvrez l'outil avec {0} ouvert : il chargera automatiquement la bonne version."
        LblScanRunningNotAccessible = "Une instance TIA Portal {0} est detectee mais inaccessible via Openness. Verifiez que l'outil et TIA Portal s'executent avec le meme niveau de privileges (les deux en administrateur, ou aucun des deux)."
        LblProject        = "Projet : {0}"
        LblPlcCount       = "{0} automate(s) detecte(s)"

        # --- Export Page ---
        PageExport        = "Export DataBlocks"
        BtnLoadDBs        = "Charger les DataBlocks"
        BtnSelectAll      = "Tout selectionner"
        BtnDeselectAll    = "Tout deselectionner"
        LblHideInstanceDB = "Masquer les DBs d'instance"
        LblDBCount        = "{0} DB(s)"
        LblExportFolder   = "Dossier :"
        LblDefaultFolder  = "Bureau (par defaut)"
        BtnExportCsv      = "Exporter Table CSV"
        TypeGlobal        = "Global"
        TypeInstance      = "Instance"
        LblPlc            = "PLC {0}"

        # --- PLC Info ---
        LblPlcName        = "PLC : {0}"
        LblPlcIp          = "IP : {0}"
        LblPlcTsap        = "TSAP : {0}"
        BtnEditPlcInfo    = "Editer"
        DlgPlcInfoTitle   = "Informations PLC"
        DlgPlcName        = "Nom du PLC :"
        DlgPlcIp          = "Adresse IP :"
        DlgPlcTsap        = "TSAP :"

        # --- CSV Export ---
        RowPlcName        = "Nom automate"
        RowIpAddress      = "Adresse IP"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Decalage"
        ColType           = "Type"
        ColDescription    = "Description"
        ColUnit           = "Unite"
        ColRepere         = "Repere"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "Export CSV termine !"
        MsgOptimizedWarning = "DB optimises ignores (aucune donnee exportee) : l'option 'Acces optimise au bloc' supprime les offsets absolus requis par l'export."
        MsgOptimizedHint  = "Pour les exporter : proprietes du bloc -> decocher 'Acces optimise au bloc', recompiler, puis relancer l'export."
        MsgXmlExportError = "{0} : Erreur export XML"
        MsgXmlParseError  = "{0} : Erreur parsing XML"

        # --- Messages ---
        MsgError          = "Erreur"
        MsgInfo           = "Information"
        MsgConfirm        = "Confirmation"
        MsgNoInstance     = "Veuillez selectionner une instance TIA Portal."
        MsgConnectFirst   = "Veuillez d'abord vous connecter a TIA Portal."
        MsgNoSelection    = "Veuillez selectionner au moins un DataBlock."
        MsgScanError      = "Erreur lors du scan :`n{0}"
        MsgConnectError   = "Erreur de connexion :`n{0}"
        MsgExportError    = "Erreur lors de l'export :`n{0}"
        MsgOpennessSecurityError = "Acces TIA Openness refuse (erreur de securite).`n`nLe compte Windows qui execute TIA Portal n'est pas membre du groupe local << Siemens TIA Openness >>.`n`nSolution (en administrateur) : ajoutez l'utilisateur a ce groupe via lusrmgr.msc, ou en ligne de commande :`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nFermez ensuite la session Windows (ou redemarrez) puis relancez TIA Portal.`n`nDetail :`n{1}"
        BtnCopyCommand    = "Copier la commande"
        MsgCopied         = "Commande copiee dans le presse-papier."
        MsgConnectOk      = "Connecte au projet : {0}`n{1} automate(s) detecte(s)"
        MsgDisconnectOk   = "Deconnecte."
        MsgLoadError      = "Erreur lors du chargement :`n{0}"
        MsgExportSuccess  = "Reussis : {0}"
        MsgExportErrors   = "Erreurs : {0}"
        MsgExportFolder   = "Dossier : {0}"
        MsgExportDetail   = "Details des erreurs :"
        MsgConfirmClose   = "Un export est en cours. Voulez-vous vraiment fermer ?"
        MsgNoProject      = "Aucun projet ouvert dans TIA Portal."
        MsgNoPlc          = "Aucun automate (PLC) trouve dans le projet."
        MsgProcessNotFound = "Processus TIA Portal introuvable."
        MsgBlockNotFound  = "{0} : Bloc introuvable"
        MsgDllRequired    = "Veuillez d'abord selectionner une version TIA Portal."
        MsgRestartRequired = "La DLL est deja chargee. Un changement de version necessite de redemarrer l'application."

        # --- Tooltips ---
        TipScan           = "Rechercher les instances TIA Portal en cours d'execution"
        TipConnect        = "Se connecter a l'instance selectionnee"
        TipDisconnect     = "Se deconnecter de TIA Portal"
        TipLoadDBs        = "Charger la liste des DataBlocks du projet"
        TipExportCsv      = "Exporter les DataBlocks selectionnes en table CSV (1 fichier par PLC)"
        TipBrowse         = "Choisir le dossier d'export"

        # --- Export Format ---
        LblExportFormat   = "Format d'export :"
        OptCsvSiemens     = "Table d'echange CSV"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Prefixe tag (opt.) :"
        LblEwonTopic      = "Topic :"
        LblEwonPage       = "Page :"
        BtnExportEwon     = "Exporter var_lst"
        TipExportEwon     = "Exporter les DataBlocks selectionnes en var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "Export var_lst termine !"
        BtnExportPcVue    = "Exporter PcVue"
        TipExportPcVue    = "Exporter au format PcVue Architect (1 fichier CSV par DB)"
        MsgExportPcVueDone = "Export PcVue termine !"
        MsgInconsistentBlock = "Bloc inconsistant --compilez le projet TIA Portal avant l'export"
        MsgOnlineModeError = "Export impossible en mode connecte (en ligne sur l'automate). Passez TIA Portal hors ligne (deconnexion de l'automate) puis relancez l'export."
        MsgOnlinePlcList  = "Automate(s) concerne(s) : {0}"

        # --- Users & roles ---
        NavUsers          = "Utilisateurs & roles"
        PageUsers         = "Utilisateurs & roles du projet"
        LblUsersInfo      = "Export / import des utilisateurs, groupes et roles personnalises du projet (Securite -> Utilisateurs et roles), avec leurs roles affectes et leurs function rights. Ecriture : TIA Portal V18+ et function right << Modify project via Openness API >>."
        BtnLoadUsers      = "Charger"
        BtnExportUsers    = "Exporter JSON..."
        BtnImportUsers    = "Importer JSON..."
        BtnDiagUsers      = "Diagnostic"
        LblUsersDryRun    = "Simulation (rien n'est ecrit)"
        LblUsersPassword  = "Mot de passe initial des utilisateurs crees :"
        LblUsersCount     = "{0} element(s)"
        KindUser          = "Utilisateur"
        KindGroup         = "Groupe"
        KindCustomRole    = "Role perso."
        KindSystemRole    = "Role systeme"
        TipLoadUsers      = "Lire les utilisateurs, groupes et roles du projet"
        TipExportUsers    = "Enregistrer utilisateurs, roles et affectations dans un fichier JSON"
        TipImportUsers    = "Creer dans le projet les roles et utilisateurs d'un fichier JSON (simulation si la case est cochee)"
        TipDiagUsers      = "Afficher le modele objet UMAC de cette version de TIA Portal (a fournir en cas de probleme)"
        TipUsersPassword  = "Les mots de passe ne sont pas exportables : ce mot de passe est donne aux utilisateurs locaux crees (a changer a la premiere connexion)."
        MsgUmacUnavailable = "Gestion des utilisateurs (UMAC) inaccessible via Openness pour cette version. Ecriture possible a partir de TIA Portal V18."
        MsgUmacServiceError = "Impossible d'acceder a la gestion des utilisateurs du projet :`n{0}"
        MsgUmacBadFile    = "Fichier non reconnu : ce n'est pas un export utilisateurs & roles de TIA Openness Tool."
        MsgUmacPasswordRequired = "mot de passe requis : renseignez le mot de passe initial"
        MsgUmacNoCreate   = "aucune methode Create(nom, ...) sur {0} (voir Diagnostic)"
        MsgUmacNoAssign   = "aucune methode d'affectation sur {0} (voir Diagnostic)"
        MsgUmacConfirmImport = "Ecrire reellement les roles et utilisateurs dans le projet {0} ?`n`nL'operation est faite dans une transaction TIA Portal (annulable par Ctrl+Z dans TIA)."
        MsgUmacExportDone = "{0} element(s) exporte(s) :`n{1}"
        MsgUmacImportDone = "Import termine.`n`nCrees : {0}`nDeja presents : {1}`nEchecs : {2}`nAffectations : {3} (echecs : {4})`n`nDetail dans le journal."
        MsgUmacDryRunDone = "Simulation terminee, rien n'a ete ecrit. Consultez le journal puis decochez << Simulation >> pour importer."
        MsgUmacError      = "Erreur utilisateurs & roles :`n{0}"
        UmacExclusiveAccess = "Import des utilisateurs et roles..."
        LogUmacCompCount  = "  {0} : {1} element(s)"
        LogUmacCompError  = "  {0} : illisible ({1})"
        LogUmacExported   = "[OK] {0} element(s) exporte(s) -> {1}"
        LogUmacModeCommit = "ECRITURE"
        LogUmacModeDryRun = "SIMULATION"
        LogUmacImportStart = "Import : {0} role(s) perso., {1} utilisateur(s), {2} element(s) ignore(s) (roles systeme, groupes) - {3}"
        LogUmacTargets    = "  Composition roles : {0} / utilisateurs : {1}"
        LogUmacNoTarget   = "  [!] Composition cible introuvable (voir Diagnostic)"
        LogUmacExists     = "  = {0} '{1}' existe deja"
        LogUmacWouldCreate = "  + {0} '{1}' serait cree"
        LogUmacCreated    = "  + {0} '{1}' cree"
        LogUmacCreateFailed = "  ! {0} '{1}' : echec ({2})"
        LogUmacRelPlan    = "      {0} / {1} : {2} a affecter, dont {3} introuvable(s) dans ce projet"
        LogUmacRelDone    = "      {0} / {1} : {2} affecte(s), {3} echec(s)"
        LogUmacRelMissing = "      {0} / {1} : relation absente sur l'objet cible, ignoree"
        LogUmacRelSkipSystem = "      {0} / {1} : role(s) systeme non affecte(s) : {2}"
        LogUmacImportDone = "[OK] Crees : {0}, deja presents : {1}, echecs : {2}, affectations : {3} (echecs : {4})"

        # --- Language ---
        LangLabel         = "Langue :"
    }

    # ============================================================
    # ENGLISH
    # ============================================================
    "EN" = @{
        # --- App ---
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "TIA Portal DataBlock Export"

        # --- Update ---
        UpdateBannerText  = "Update v{0} available. Automatic download failed (check your network connection)."
        BtnUpdateDownload = "Download"
        TipUpdateDownload = "Open the latest release download page"

        # --- Navigation ---
        NavConnection     = "Connection"
        NavExport         = "Export DataBlocks"

        # --- Version ---
        LblVersion        = "TIA Portal Version:"
        LblNoVersion      = "No TIA Portal version detected."
        LblDllError       = "DLL loading error"
        LblVersionLocked  = "Version locked (connected)"
        LblVersionPending = "Version {0} selected (loaded on first scan)."
        LblVersionLoadedLocked = "Version {0} loaded. Restart the tool to change it."

        # --- Connection Page ---
        PageConnection    = "TIA Portal Connection"
        BtnScan           = "Scan TIA Portal instances"
        LblInstances      = "Available instances"
        BtnConnect        = "Connect"
        BtnDisconnect     = "Disconnect"
        LblConnected      = "Connected"
        LblDisconnected   = "Disconnected"
        LblScanResult     = "{0} instance(s) found"
        LblNoInstance     = "No TIA Portal instance found"
        LblScanVersionMismatch = "TIA Portal {0} is open but the loaded version is {1}. Close and reopen the tool with {0} running: it will load the correct version automatically."
        LblScanRunningNotAccessible = "A TIA Portal {0} instance is detected but not accessible via Openness. Make sure the tool and TIA Portal run with the same privilege level (both as administrator, or neither)."
        LblProject        = "Project: {0}"
        LblPlcCount       = "{0} PLC(s) detected"

        # --- Export Page ---
        PageExport        = "Export DataBlocks"
        BtnLoadDBs        = "Load DataBlocks"
        BtnSelectAll      = "Select all"
        BtnDeselectAll    = "Deselect all"
        LblHideInstanceDB = "Hide instance DBs"
        LblDBCount        = "{0} DB(s)"
        LblExportFolder   = "Folder:"
        LblDefaultFolder  = "Desktop (default)"
        BtnExportCsv      = "Export CSV Table"
        TypeGlobal        = "Global"
        TypeInstance      = "Instance"
        LblPlc            = "PLC {0}"

        # --- PLC Info ---
        LblPlcName        = "PLC: {0}"
        LblPlcIp          = "IP: {0}"
        LblPlcTsap        = "TSAP: {0}"
        BtnEditPlcInfo    = "Edit"
        DlgPlcInfoTitle   = "PLC Information"
        DlgPlcName        = "PLC Name:"
        DlgPlcIp          = "IP Address:"
        DlgPlcTsap        = "TSAP:"

        # --- CSV Export ---
        RowPlcName        = "PLC Name"
        RowIpAddress      = "IP Address"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Offset"
        ColType           = "Type"
        ColDescription    = "Description"
        ColUnit           = "Unit"
        ColRepere         = "Reference"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "CSV export completed!"
        MsgOptimizedWarning = "Optimized DBs skipped (no data exported): 'Optimized block access' removes the absolute offsets this tool needs."
        MsgOptimizedHint  = "To export them: block properties -> uncheck 'Optimized block access', recompile, then run the export again."
        MsgXmlExportError = "{0}: XML export error"
        MsgXmlParseError  = "{0}: XML parsing error"

        # --- Messages ---
        MsgError          = "Error"
        MsgInfo           = "Information"
        MsgConfirm        = "Confirmation"
        MsgNoInstance     = "Please select a TIA Portal instance."
        MsgConnectFirst   = "Please connect to TIA Portal first."
        MsgNoSelection    = "Please select at least one DataBlock."
        MsgScanError      = "Error during scan:`n{0}"
        MsgConnectError   = "Connection error:`n{0}"
        MsgExportError    = "Export error:`n{0}"
        MsgOpennessSecurityError = "TIA Openness access denied (security error).`n`nThe Windows account running TIA Portal is not a member of the local group << Siemens TIA Openness >>.`n`nFix (as administrator): add the user to that group via lusrmgr.msc, or from the command line:`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nThen sign out of Windows (or reboot) and restart TIA Portal.`n`nDetails:`n{1}"
        BtnCopyCommand    = "Copy command"
        MsgCopied         = "Command copied to clipboard."
        MsgConnectOk      = "Connected to project: {0}`n{1} PLC(s) detected"
        MsgDisconnectOk   = "Disconnected."
        MsgLoadError      = "Error while loading:`n{0}"
        MsgExportSuccess  = "Successful: {0}"
        MsgExportErrors   = "Errors: {0}"
        MsgExportFolder   = "Folder: {0}"
        MsgExportDetail   = "Error details:"
        MsgConfirmClose   = "An export is in progress. Do you really want to close?"
        MsgNoProject      = "No project open in TIA Portal."
        MsgNoPlc          = "No PLC found in the project."
        MsgProcessNotFound = "TIA Portal process not found."
        MsgBlockNotFound  = "{0}: Block not found"
        MsgDllRequired    = "Please select a TIA Portal version first."
        MsgRestartRequired = "DLL already loaded. Changing version requires restarting the application."

        # --- Tooltips ---
        TipScan           = "Search for running TIA Portal instances"
        TipConnect        = "Connect to the selected instance"
        TipDisconnect     = "Disconnect from TIA Portal"
        TipLoadDBs        = "Load the project's DataBlock list"
        TipExportCsv      = "Export selected DataBlocks as CSV table (1 file per PLC)"
        TipBrowse         = "Choose the export folder"

        # --- Export Format ---
        LblExportFormat   = "Export format:"
        OptCsvSiemens     = "CSV Exchange Table"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Tag prefix (opt.):"
        LblEwonTopic      = "Topic:"
        LblEwonPage       = "Page:"
        BtnExportEwon     = "Export var_lst"
        TipExportEwon     = "Export selected DataBlocks as var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "var_lst export completed!"
        BtnExportPcVue    = "Export PcVue"
        TipExportPcVue    = "Export as PcVue Architect format (1 CSV file per DB)"
        MsgExportPcVueDone = "PcVue export completed!"
        MsgInconsistentBlock = "Inconsistent block --compile the TIA Portal project before exporting"
        MsgOnlineModeError = "Export is not possible in online mode (connected to the PLC). Switch TIA Portal offline (disconnect from the PLC) then export again."
        MsgOnlinePlcList  = "Affected PLC(s): {0}"

        # --- Users & roles ---
        NavUsers          = "Users & roles"
        PageUsers         = "Project users & roles"
        LblUsersInfo      = "Export / import the project's users, groups and custom roles (Security -> Users and roles), with their assigned roles and function rights. Writing requires TIA Portal V18+ and the << Modify project via Openness API >> function right."
        BtnLoadUsers      = "Load"
        BtnExportUsers    = "Export JSON..."
        BtnImportUsers    = "Import JSON..."
        BtnDiagUsers      = "Diagnostics"
        LblUsersDryRun    = "Dry run (nothing is written)"
        LblUsersPassword  = "Initial password for created users:"
        LblUsersCount     = "{0} item(s)"
        KindUser          = "User"
        KindGroup         = "Group"
        KindCustomRole    = "Custom role"
        KindSystemRole    = "System role"
        TipLoadUsers      = "Read the project's users, groups and roles"
        TipExportUsers    = "Save users, roles and assignments to a JSON file"
        TipImportUsers    = "Create the roles and users of a JSON file in the project (dry run when the box is checked)"
        TipDiagUsers      = "Show the UMAC object model of this TIA Portal version (to provide when reporting an issue)"
        TipUsersPassword  = "Passwords cannot be exported: this password is given to the created local users (to be changed at first login)."
        MsgUmacUnavailable = "User management (UMAC) is not accessible through Openness for this version. Writing requires TIA Portal V18 or later."
        MsgUmacServiceError = "Cannot access the project's user management:`n{0}"
        MsgUmacBadFile    = "Unrecognized file: this is not a TIA Openness Tool users & roles export."
        MsgUmacPasswordRequired = "password required: fill in the initial password"
        MsgUmacNoCreate   = "no Create(name, ...) method on {0} (see Diagnostics)"
        MsgUmacNoAssign   = "no assignment method on {0} (see Diagnostics)"
        MsgUmacConfirmImport = "Really write the roles and users into project {0}?`n`nThe operation runs in a TIA Portal transaction (can be undone with Ctrl+Z in TIA)."
        MsgUmacExportDone = "{0} item(s) exported:`n{1}"
        MsgUmacImportDone = "Import finished.`n`nCreated: {0}`nAlready present: {1}`nFailed: {2}`nAssignments: {3} (failed: {4})`n`nSee the log for details."
        MsgUmacDryRunDone = "Dry run finished, nothing was written. Check the log, then uncheck << Dry run >> to import."
        MsgUmacError      = "Users & roles error:`n{0}"
        UmacExclusiveAccess = "Importing users and roles..."
        LogUmacCompCount  = "  {0}: {1} item(s)"
        LogUmacCompError  = "  {0}: unreadable ({1})"
        LogUmacExported   = "[OK] {0} item(s) exported -> {1}"
        LogUmacModeCommit = "WRITE"
        LogUmacModeDryRun = "DRY RUN"
        LogUmacImportStart = "Import: {0} custom role(s), {1} user(s), {2} item(s) skipped (system roles, groups) - {3}"
        LogUmacTargets    = "  Roles composition: {0} / users: {1}"
        LogUmacNoTarget   = "  [!] Target composition not found (see Diagnostics)"
        LogUmacExists     = "  = {0} '{1}' already exists"
        LogUmacWouldCreate = "  + {0} '{1}' would be created"
        LogUmacCreated    = "  + {0} '{1}' created"
        LogUmacCreateFailed = "  ! {0} '{1}': failed ({2})"
        LogUmacRelPlan    = "      {0} / {1}: {2} to assign, {3} not found in this project"
        LogUmacRelDone    = "      {0} / {1}: {2} assigned, {3} failed"
        LogUmacRelMissing = "      {0} / {1}: relation missing on the target object, skipped"
        LogUmacRelSkipSystem = "      {0} / {1}: system role(s) not assigned: {2}"
        LogUmacImportDone = "[OK] Created: {0}, already present: {1}, failed: {2}, assignments: {3} (failed: {4})"

        # --- Language ---
        LangLabel         = "Language:"
    }

    # ============================================================
    # ESPANOL
    # ============================================================
    "ES" = @{
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "Exportar DataBlocks TIA Portal"
        UpdateBannerText  = "Actualizacion v{0} disponible. La descarga automatica fallo (verifique la conexion de red)."
        BtnUpdateDownload = "Descargar"
        TipUpdateDownload = "Abrir la pagina de descarga de la ultima version"
        NavConnection     = "Conexion"
        NavExport         = "Exportar DataBlocks"
        LblVersion        = "Version TIA Portal:"
        LblNoVersion      = "No se detecto ninguna version de TIA Portal."
        LblDllError       = "Error al cargar DLL"
        LblVersionLocked  = "Version bloqueada (conectado)"
        LblVersionPending = "Version {0} seleccionada (se carga en la primera busqueda)."
        LblVersionLoadedLocked = "Version {0} cargada. Reinicie la herramienta para cambiarla."
        PageConnection    = "Conexion TIA Portal"
        BtnScan           = "Buscar instancias TIA Portal"
        LblInstances      = "Instancias disponibles"
        BtnConnect        = "Conectar"
        BtnDisconnect     = "Desconectar"
        LblConnected      = "Conectado"
        LblDisconnected   = "Desconectado"
        LblScanResult     = "{0} instancia(s) encontrada(s)"
        LblNoInstance     = "No se encontro ninguna instancia de TIA Portal"
        LblScanVersionMismatch = "TIA Portal {0} esta abierto pero la version cargada es {1}. Cierre y vuelva a abrir la herramienta con {0} abierto: cargara automaticamente la version correcta."
        LblScanRunningNotAccessible = "Se detecta una instancia de TIA Portal {0} pero no es accesible via Openness. Asegurese de que la herramienta y TIA Portal se ejecuten con el mismo nivel de privilegios (ambos como administrador, o ninguno)."
        LblProject        = "Proyecto: {0}"
        LblPlcCount       = "{0} PLC(s) detectado(s)"
        PageExport        = "Exportar DataBlocks"
        BtnLoadDBs        = "Cargar DataBlocks"
        BtnSelectAll      = "Seleccionar todo"
        BtnDeselectAll    = "Deseleccionar todo"
        LblHideInstanceDB = "Ocultar DBs de instancia"
        LblDBCount        = "{0} DB(s)"
        LblExportFolder   = "Carpeta:"
        LblDefaultFolder  = "Escritorio (por defecto)"
        BtnExportCsv      = "Exportar Tabla CSV"
        TypeGlobal        = "Global"
        TypeInstance      = "Instancia"
        LblPlc            = "PLC {0}"
        LblPlcName        = "PLC: {0}"
        LblPlcIp          = "IP: {0}"
        LblPlcTsap        = "TSAP: {0}"
        BtnEditPlcInfo    = "Editar"
        DlgPlcInfoTitle   = "Informacion del PLC"
        DlgPlcName        = "Nombre del PLC:"
        DlgPlcIp          = "Direccion IP:"
        DlgPlcTsap        = "TSAP:"
        RowPlcName        = "Nombre PLC"
        RowIpAddress      = "Direccion IP"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Desplazamiento"
        ColType           = "Tipo"
        ColDescription    = "Descripcion"
        ColUnit           = "Unidad"
        ColRepere         = "Referencia"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "Exportacion CSV completada!"
        MsgOptimizedWarning = "DBs optimizados omitidos (sin datos exportados): 'Acceso optimizado al bloque' elimina los offsets absolutos que necesita esta herramienta."
        MsgOptimizedHint  = "Para exportarlos: propiedades del bloque -> desmarcar 'Acceso optimizado al bloque', recompilar y volver a ejecutar la exportacion."
        MsgXmlExportError = "{0}: Error exportacion XML"
        MsgXmlParseError  = "{0}: Error parsing XML"
        MsgError          = "Error"
        MsgInfo           = "Informacion"
        MsgConfirm        = "Confirmacion"
        MsgNoInstance     = "Por favor seleccione una instancia de TIA Portal."
        MsgConnectFirst   = "Por favor conectese primero a TIA Portal."
        MsgNoSelection    = "Por favor seleccione al menos un DataBlock."
        MsgScanError      = "Error durante la busqueda:`n{0}"
        MsgConnectError   = "Error de conexion:`n{0}"
        MsgExportError    = "Error durante la exportacion:`n{0}"
        MsgOpennessSecurityError = "Acceso TIA Openness denegado (error de seguridad).`n`nLa cuenta de Windows que ejecuta TIA Portal no es miembro del grupo local << Siemens TIA Openness >>.`n`nSolucion (como administrador): anada el usuario a ese grupo mediante lusrmgr.msc, o por linea de comandos:`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nLuego cierre la sesion de Windows (o reinicie) y vuelva a iniciar TIA Portal.`n`nDetalle:`n{1}"
        BtnCopyCommand    = "Copiar el comando"
        MsgCopied         = "Comando copiado al portapapeles."
        MsgConnectOk      = "Conectado al proyecto: {0}`n{1} PLC(s) detectado(s)"
        MsgDisconnectOk   = "Desconectado."
        MsgLoadError      = "Error al cargar:`n{0}"
        MsgExportSuccess  = "Exitosos: {0}"
        MsgExportErrors   = "Errores: {0}"
        MsgExportFolder   = "Carpeta: {0}"
        MsgExportDetail   = "Detalles de errores:"
        MsgConfirmClose   = "Una exportacion esta en curso. Desea cerrar?"
        MsgNoProject      = "No hay proyecto abierto en TIA Portal."
        MsgNoPlc          = "No se encontro ningun PLC en el proyecto."
        MsgProcessNotFound = "Proceso TIA Portal no encontrado."
        MsgBlockNotFound  = "{0}: Bloque no encontrado"
        MsgDllRequired    = "Por favor seleccione una version de TIA Portal primero."
        MsgRestartRequired = "DLL ya cargada. Cambiar de version requiere reiniciar la aplicacion."
        TipScan           = "Buscar instancias de TIA Portal en ejecucion"
        TipConnect        = "Conectar a la instancia seleccionada"
        TipDisconnect     = "Desconectar de TIA Portal"
        TipLoadDBs        = "Cargar la lista de DataBlocks del proyecto"
        TipExportCsv      = "Exportar DataBlocks seleccionados como tabla CSV (1 archivo por PLC)"
        TipBrowse         = "Elegir la carpeta de exportacion"
        # --- Export Format ---
        LblExportFormat   = "Formato de exportacion:"
        OptCsvSiemens     = "Tabla de intercambio CSV"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Prefijo tag (opc.):"
        LblEwonTopic      = "Topic:"
        LblEwonPage       = "Pagina:"
        BtnExportEwon     = "Exportar var_lst"
        TipExportEwon     = "Exportar DataBlocks seleccionados como var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "Exportacion var_lst completada!"
        BtnExportPcVue    = "Exportar PcVue"
        TipExportPcVue    = "Exportar en formato PcVue Architect (1 archivo CSV por DB)"
        MsgExportPcVueDone = "Exportacion PcVue completada!"
        MsgInconsistentBlock = "Bloque inconsistente --compile el proyecto TIA Portal antes de exportar"
        MsgOnlineModeError = "La exportacion no es posible en modo en linea (conectado al PLC). Ponga TIA Portal fuera de linea (desconecte del PLC) y vuelva a exportar."
        MsgOnlinePlcList  = "PLC(s) afectado(s): {0}"
        LangLabel         = "Idioma:"
    }

    # ============================================================
    # ITALIANO
    # ============================================================
    "IT" = @{
        AppTitle          = "TIA Openness Tool"
        AppSubtitle       = "Esportazione DataBlocks TIA Portal"
        UpdateBannerText  = "Aggiornamento v{0} disponibile. Il download automatico e fallito (verificare la connessione di rete)."
        BtnUpdateDownload = "Scarica"
        TipUpdateDownload = "Aprire la pagina di download dell'ultima versione"
        NavConnection     = "Connessione"
        NavExport         = "Esporta DataBlocks"
        LblVersion        = "Versione TIA Portal:"
        LblNoVersion      = "Nessuna versione di TIA Portal rilevata."
        LblDllError       = "Errore caricamento DLL"
        LblVersionLocked  = "Versione bloccata (connesso)"
        LblVersionPending = "Versione {0} selezionata (caricata alla prima scansione)."
        LblVersionLoadedLocked = "Versione {0} caricata. Riavvia lo strumento per cambiarla."
        PageConnection    = "Connessione TIA Portal"
        BtnScan           = "Scansiona istanze TIA Portal"
        LblInstances      = "Istanze disponibili"
        BtnConnect        = "Connetti"
        BtnDisconnect     = "Disconnetti"
        LblConnected      = "Connesso"
        LblDisconnected   = "Disconnesso"
        LblScanResult     = "{0} istanza(e) trovata(e)"
        LblNoInstance     = "Nessuna istanza TIA Portal trovata"
        LblScanVersionMismatch = "TIA Portal {0} e aperto ma la versione caricata e {1}. Chiudi e riapri lo strumento con {0} aperto: carichera automaticamente la versione corretta."
        LblScanRunningNotAccessible = "Un'istanza TIA Portal {0} e rilevata ma non accessibile via Openness. Verifica che lo strumento e TIA Portal vengano eseguiti con lo stesso livello di privilegi (entrambi come amministratore, o nessuno dei due)."
        LblProject        = "Progetto: {0}"
        LblPlcCount       = "{0} PLC rilevati"
        PageExport        = "Esporta DataBlocks"
        BtnLoadDBs        = "Carica DataBlocks"
        BtnSelectAll      = "Seleziona tutto"
        BtnDeselectAll    = "Deseleziona tutto"
        LblHideInstanceDB = "Nascondi DB di istanza"
        LblDBCount        = "{0} DB"
        LblExportFolder   = "Cartella:"
        LblDefaultFolder  = "Desktop (predefinito)"
        BtnExportCsv      = "Esporta Tabella CSV"
        TypeGlobal        = "Globale"
        TypeInstance      = "Istanza"
        LblPlc            = "PLC {0}"
        LblPlcName        = "PLC: {0}"
        LblPlcIp          = "IP: {0}"
        LblPlcTsap        = "TSAP: {0}"
        BtnEditPlcInfo    = "Modifica"
        DlgPlcInfoTitle   = "Informazioni PLC"
        DlgPlcName        = "Nome PLC:"
        DlgPlcIp          = "Indirizzo IP:"
        DlgPlcTsap        = "TSAP:"
        RowPlcName        = "Nome PLC"
        RowIpAddress      = "Indirizzo IP"
        RowTsap           = "TSAP"
        ColTag            = "TAG"
        ColDB             = "DB"
        ColOffset         = "Offset"
        ColType           = "Tipo"
        ColDescription    = "Descrizione"
        ColUnit           = "Unita"
        ColRepere         = "Riferimento"
        ColCoef           = "Coef"
        MsgExportCsvDone  = "Esportazione CSV completata!"
        MsgOptimizedWarning = "DB ottimizzati ignorati (nessun dato esportato): 'Accesso ottimizzato al blocco' rimuove gli offset assoluti richiesti da questo strumento."
        MsgOptimizedHint  = "Per esportarli: proprieta del blocco -> deselezionare 'Accesso ottimizzato al blocco', ricompilare, quindi rilanciare l'esportazione."
        MsgXmlExportError = "{0}: Errore esportazione XML"
        MsgXmlParseError  = "{0}: Errore parsing XML"
        MsgError          = "Errore"
        MsgInfo           = "Informazione"
        MsgConfirm        = "Conferma"
        MsgNoInstance     = "Selezionare un'istanza TIA Portal."
        MsgConnectFirst   = "Connettersi prima a TIA Portal."
        MsgNoSelection    = "Selezionare almeno un DataBlock."
        MsgScanError      = "Errore durante la scansione:`n{0}"
        MsgConnectError   = "Errore di connessione:`n{0}"
        MsgExportError    = "Errore durante l'esportazione:`n{0}"
        MsgOpennessSecurityError = "Accesso TIA Openness negato (errore di sicurezza).`n`nL'account Windows che esegue TIA Portal non e membro del gruppo locale << Siemens TIA Openness >>.`n`nSoluzione (come amministratore): aggiungere l'utente a tale gruppo tramite lusrmgr.msc, o da riga di comando:`n  net localgroup `"Siemens TIA Openness`" `"{0}`" /add`n`nQuindi disconnettersi da Windows (o riavviare) e riavviare TIA Portal.`n`nDettaglio:`n{1}"
        BtnCopyCommand    = "Copia il comando"
        MsgCopied         = "Comando copiato negli appunti."
        MsgConnectOk      = "Connesso al progetto: {0}`n{1} PLC rilevati"
        MsgDisconnectOk   = "Disconnesso."
        MsgLoadError      = "Errore durante il caricamento:`n{0}"
        MsgExportSuccess  = "Riusciti: {0}"
        MsgExportErrors   = "Errori: {0}"
        MsgExportFolder   = "Cartella: {0}"
        MsgExportDetail   = "Dettagli errori:"
        MsgConfirmClose   = "Un'esportazione e in corso. Vuoi davvero chiudere?"
        MsgNoProject      = "Nessun progetto aperto in TIA Portal."
        MsgNoPlc          = "Nessun PLC trovato nel progetto."
        MsgProcessNotFound = "Processo TIA Portal non trovato."
        MsgBlockNotFound  = "{0}: Blocco non trovato"
        MsgDllRequired    = "Selezionare prima una versione di TIA Portal."
        MsgRestartRequired = "DLL gia caricata. Cambiare versione richiede il riavvio dell'applicazione."
        TipScan           = "Cercare istanze TIA Portal in esecuzione"
        TipConnect        = "Connettersi all'istanza selezionata"
        TipDisconnect     = "Disconnettersi da TIA Portal"
        TipLoadDBs        = "Caricare la lista dei DataBlocks del progetto"
        TipExportCsv      = "Esportare i DataBlocks selezionati come tabella CSV (1 file per PLC)"
        TipBrowse         = "Scegliere la cartella di esportazione"
        # --- Export Format ---
        LblExportFormat   = "Formato di esportazione:"
        OptCsvSiemens     = "Tabella di scambio CSV"
        OptVarLstEwon     = "var_lst (Ewon)"
        OptPcVue          = "PcVue Architect (.csv)"
        LblEwonRepere     = "Prefisso tag (opz.):"
        LblEwonTopic      = "Topic:"
        LblEwonPage       = "Pagina:"
        BtnExportEwon     = "Esporta var_lst"
        TipExportEwon     = "Esportare i DataBlocks selezionati come var_lst.csv (Ewon Flexy)"
        MsgExportEwonDone = "Esportazione var_lst completata!"
        BtnExportPcVue    = "Esporta PcVue"
        TipExportPcVue    = "Esportare in formato PcVue Architect (1 file CSV per DB)"
        MsgExportPcVueDone = "Esportazione PcVue completata!"
        MsgInconsistentBlock = "Blocco inconsistente --compilare il progetto TIA Portal prima dell'esportazione"
        MsgOnlineModeError = "Esportazione non possibile in modalita online (connessi al PLC). Mettere TIA Portal offline (disconnettere dal PLC) e riprovare l'esportazione."
        MsgOnlinePlcList  = "PLC interessati: {0}"
        LangLabel         = "Lingua:"
    }
}

function T([string]$Key) {
    $s = $Script:Strings[$Script:CurrentLanguage]
    if ($s -and $s.ContainsKey($Key)) { return $s[$Key] }
    # Fallback to French
    $fr = $Script:Strings["FR"]
    if ($fr -and $fr.ContainsKey($Key)) { return $fr[$Key] }
    return "[$Key]"
}

function Set-Language([string]$Lang) {
    if ($Script:Strings.ContainsKey($Lang)) {
        $Script:CurrentLanguage = $Lang
        Set-AppStateValue -Key "Language" -Value $Lang
    }
}

function Get-Language { return $Script:CurrentLanguage }
